### ISSUE TITLE
4.2

### ISSUE THREAD

**Issue by GooglePlugin** [pofycn/JB_Crack_Setting#1]
JetbrainsIdesCrack-4.2 is released. Where can I find it?

**Comment by Sn0wl3r0ker** [comment]
> JetbrainsIdesCrack-4.2 is released. Where can I find it?

You can find it on http://idea.lanyus.com/
P.S. if you can plz support genuine software : )

**Comment by GooglePlugin** [comment]
Okay, thank you.

**Comment by pofycn** [comment]
@GooglePlugin I will update it lately, thanks for your notofication.

**Comment by GooglePlugin** [comment]
You're welcome.
